"""Read pair and split manifests generated by the data audit gate."""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class PairRecord:
    """One clean/noisy pair plus optional metadata."""

    pair_key: str
    clean_path: Path
    noisy_path: Path
    metadata: dict[str, str]


def load_pair_manifest(path: str | Path, base_dir: str | Path | None = None) -> list[PairRecord]:
    """Load `pairs.csv` and resolve image paths."""

    manifest_path = Path(path)
    root = Path(base_dir) if base_dir is not None else manifest_path.parent.parent
    records: list[PairRecord] = []
    with manifest_path.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        required = {"pair_key", "clean_path", "noisy_path"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Pair manifest missing required columns: {sorted(missing)}")
        for row in reader:
            pair_key = row["pair_key"]
            clean_path = resolve_path(row["clean_path"], root)
            noisy_path = resolve_path(row["noisy_path"], root)
            metadata = {
                key: value
                for key, value in row.items()
                if key not in {"pair_key", "clean_path", "noisy_path"} and value not in (None, "")
            }
            records.append(PairRecord(pair_key=pair_key, clean_path=clean_path, noisy_path=noisy_path, metadata=metadata))
    return records


def load_split_manifest(path: str | Path) -> dict[str, list[str]]:
    """Load `splits.yaml` without requiring PyYAML."""

    text = Path(path).read_text(encoding="utf-8")
    try:
        import yaml

        loaded = yaml.safe_load(text) or {}
        return {str(key): [str(item) for item in (value or [])] for key, value in loaded.items()}
    except Exception:
        return parse_simple_split_yaml(text)


def parse_simple_split_yaml(text: str) -> dict[str, list[str]]:
    splits: dict[str, list[str]] = {}
    current: str | None = None
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0].rstrip()
        if not line:
            continue
        if not line.startswith(" ") and line.endswith(":"):
            current = line[:-1].strip()
            splits[current] = []
            continue
        if current is not None and line.strip().startswith("- "):
            splits[current].append(line.strip()[2:].strip())
    return splits


def resolve_split_records(
    pairs_csv: str | Path,
    splits_yaml: str | Path,
    split: str,
    base_dir: str | Path | None = None,
) -> list[PairRecord]:
    """Return pair records belonging to one split."""

    records = load_pair_manifest(pairs_csv, base_dir=base_dir)
    splits = load_split_manifest(splits_yaml)
    if split not in splits:
        raise KeyError(f"Split {split!r} not found. Available: {sorted(splits)}")
    wanted = set(splits[split])
    by_key = {record.pair_key: record for record in records}
    missing = sorted(wanted.difference(by_key))
    if missing:
        raise ValueError(f"Split {split!r} references unknown pair keys: {missing[:10]}")
    return [by_key[key] for key in splits[split]]


def resolve_path(value: str, root: Path) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return (root / path).resolve()


def records_to_rows(records: list[PairRecord]) -> list[dict[str, Any]]:
    """Convert records back to plain rows for scripts/reports."""

    return [
        {
            "pair_key": record.pair_key,
            "clean_path": str(record.clean_path),
            "noisy_path": str(record.noisy_path),
            **record.metadata,
        }
        for record in records
    ]
